<a href="https://colab.research.google.com/github/rikdantas/Aprendizagem-de-Maquinas/blob/main/IMD1101/Pratica_05/Pratica05_Comit%C3%AA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prática 05 - Prática de Comitês de Classificadores
Nesse notebook será desenvolvida a prática 05 que é relacionada com comitê de classificadores. A base que vai ser usada é a PCA_CNN_VGG19_128_avg que mostrou o melhor desempenho nas últimas duas práticas.

Aluno: Paulo Ricardo Dantas

In [37]:
# Importando as bibliotecas
import numpy as np
import pandas as pd
import gdown
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

## Preparando o dataset para os testes

In [2]:
# Baixando o dataset
gdown.download('https://drive.google.com/uc?id=17BJNdaH_8fCYTJn-l-QH7ayRaLuWYxQ6', 'PCA_CNN_VGG19_128_avg.csv', quiet=True)

# Importando o dataset
dataset = pd.read_csv('PCA_CNN_VGG19_128_avg.csv', encoding='utf-8')

# Separando os atributos e a classe
x = dataset.drop(columns=['class'])  # Remove apenas a coluna 'class'
y = dataset['class']  # Seleciona a coluna 'class' como a variável alvo

# Dividindo o dataset em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=19)

## Aplicando os Comitês

### Bagging padrão


#### Árvore de decisão

In [3]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=10, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.6375
Matriz de confusão para 10 estimadores:
[[73 57]
 [30 80]]


In [4]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=20, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.6625
Matriz de confusão para 20 estimadores:
[[83 47]
 [34 76]]


In [5]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=30, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.65
Matriz de confusão para 30 estimadores:
[[77 53]
 [31 79]]


#### k-NN

In [8]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=10, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.6
Matriz de confusão para 10 estimadores:
[[76 54]
 [42 68]]


In [9]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=20, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.5875
Matriz de confusão para 20 estimadores:
[[78 52]
 [47 63]]


In [10]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=30, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.5708333333333333
Matriz de confusão para 30 estimadores:
[[71 59]
 [44 66]]


#### Naive-Bayes

In [11]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=10, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.6708333333333333
Matriz de confusão para 10 estimadores:
[[78 52]
 [27 83]]


In [12]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=20, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.6791666666666667
Matriz de confusão para 20 estimadores:
[[78 52]
 [25 85]]


In [13]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=30, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6708333333333333
Matriz de confusão para 30 estimadores:
[[76 54]
 [25 85]]


#### Multilayer Perceptron

In [14]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=10, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.5291666666666667
Matriz de confusão para 10 estimadores:
[[43 87]
 [26 84]]


In [15]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=20, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.5416666666666666
Matriz de confusão para 20 estimadores:
[[34 96]
 [14 96]]


In [16]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=30, max_features=1.0, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.5333333333333333
Matriz de confusão para 30 estimadores:
[[ 29 101]
 [ 11  99]]


### Bagging feature selection


#### Árvore de decisão

In [29]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=10, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.6583333333333333
Matriz de confusão para 10 estimadores:
[[80 50]
 [32 78]]


In [18]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=20, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.7
Matriz de confusão para 20 estimadores:
[[79 51]
 [21 89]]


In [19]:
# Instanciando bagging com DecisionTree
bgclassifier = BaggingClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                    n_estimators=30, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6833333333333333
Matriz de confusão para 30 estimadores:
[[79 51]
 [25 85]]


#### k-NN

In [20]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=10, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.5875
Matriz de confusão para 10 estimadores:
[[72 58]
 [41 69]]


In [21]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=20, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.6375
Matriz de confusão para 20 estimadores:
[[80 50]
 [37 73]]


In [22]:
# Instanciando bagging com k-NN
bgclassifier = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=3, metric='euclidean'),
                                    n_estimators=30, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6083333333333333
Matriz de confusão para 30 estimadores:
[[74 56]
 [38 72]]


#### Naive-Bayes

In [23]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=10, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.675
Matriz de confusão para 10 estimadores:
[[81 49]
 [29 81]]


In [24]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=20, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.6541666666666667
Matriz de confusão para 20 estimadores:
[[73 57]
 [26 84]]


In [25]:
# Instanciando bagging com GaussianNB
bgclassifier = BaggingClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                    n_estimators=30, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6708333333333333
Matriz de confusão para 30 estimadores:
[[73 57]
 [22 88]]


#### Multilayer Perceptron

In [26]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=10, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.5125
Matriz de confusão para 10 estimadores:
[[ 15 115]
 [  2 108]]


In [27]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=20, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.4791666666666667
Matriz de confusão para 20 estimadores:
[[  6 124]
 [  1 109]]


In [28]:
# Instanciando bagging com MLPClassifier
bgclassifier = BaggingClassifier(estimator=MLPClassifier(hidden_layer_sizes=100, activation='tanh', solver= 'sgd',
                                                         max_iter=1500, learning_rate_init=0.001),
                                                         n_estimators=30, max_features=0.5, max_samples=1.0)
bgclassifier.fit(X_train, y_train)
y_pred = bgclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.4666666666666667
Matriz de confusão para 30 estimadores:
[[  3 127]
 [  1 109]]


### Boosting

#### Árvore de decisão

In [31]:
# Instanciando Boosting com DecisionTree
adaclassifier = AdaBoostClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                  n_estimators=10, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.675
Matriz de confusão para 10 estimadores:
[[81 49]
 [29 81]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


In [32]:
# Instanciando Boosting com DecisionTree
adaclassifier = AdaBoostClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                  n_estimators=20, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.7166666666666667
Matriz de confusão para 20 estimadores:
[[86 44]
 [24 86]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


In [33]:
# Instanciando Boosting com DecisionTree
adaclassifier = AdaBoostClassifier(estimator=DecisionTreeClassifier(criterion="entropy", max_depth=6),
                                  n_estimators=30, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


Acurácia do modelo com 30 estimadores: 0.7166666666666667
Matriz de confusão para 30 estimadores:
[[87 43]
 [25 85]]


#### Naive Bayes

In [34]:
# Instanciando Boosting com GaussianNB
adaclassifier = AdaBoostClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                   n_estimators=10, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.7208333333333333
Matriz de confusão para 10 estimadores:
[[94 36]
 [31 79]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


In [35]:
# Instanciando Boosting com GaussianNB
adaclassifier = AdaBoostClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                   n_estimators=20, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.7208333333333333
Matriz de confusão para 20 estimadores:
[[94 36]
 [31 79]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


In [36]:
# Instanciando Boosting com GaussianNB
adaclassifier = AdaBoostClassifier(estimator=GaussianNB(priors=None, var_smoothing=1e-09),
                                   n_estimators=30, learning_rate=0.5, algorithm="SAMME")
adaclassifier.fit(X_train, y_train)
y_pred = adaclassifier.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.7208333333333333
Matriz de confusão para 30 estimadores:
[[94 36]
 [31 79]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:514: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


### Random Forest

#### Gini

In [47]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=10, criterion="gini", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.7083333333333334
Matriz de confusão para 10 estimadores:
[[94 36]
 [34 76]]


In [48]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=20, criterion="gini", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.7
Matriz de confusão para 20 estimadores:
[[89 41]
 [31 79]]


In [49]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=30, criterion="gini", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.7083333333333334
Matriz de confusão para 30 estimadores:
[[92 38]
 [32 78]]


In [50]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=100, criterion="gini", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 100 estimadores:", acuracia)

# Matriz de confusão para 100%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 100 estimadores:")
print(cm)

Acurácia do modelo com 100 estimadores: 0.7083333333333334
Matriz de confusão para 100 estimadores:
[[91 39]
 [31 79]]


#### Entropy

In [51]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=10, criterion="entropy", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.7041666666666667
Matriz de confusão para 10 estimadores:
[[94 36]
 [35 75]]


In [52]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=20, criterion="entropy", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.65
Matriz de confusão para 20 estimadores:
[[82 48]
 [36 74]]


In [53]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=30, criterion="entropy", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6791666666666667
Matriz de confusão para 30 estimadores:
[[86 44]
 [33 77]]


In [54]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 100 estimadores:", acuracia)

# Matriz de confusão para 100%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 100 estimadores:")
print(cm)

Acurácia do modelo com 100 estimadores: 0.6791666666666667
Matriz de confusão para 100 estimadores:
[[86 44]
 [33 77]]


#### Log_loss

In [55]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=10, criterion="log_loss", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 10 estimadores:", acuracia)

# Matriz de confusão para 10%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 10 estimadores:")
print(cm)

Acurácia do modelo com 10 estimadores: 0.675
Matriz de confusão para 10 estimadores:
[[85 45]
 [33 77]]


In [56]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=20, criterion="log_loss", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 20 estimadores:", acuracia)

# Matriz de confusão para 20%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 20 estimadores:")
print(cm)

Acurácia do modelo com 20 estimadores: 0.6916666666666667
Matriz de confusão para 20 estimadores:
[[91 39]
 [35 75]]


In [57]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=30, criterion="log_loss", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 30 estimadores:", acuracia)

# Matriz de confusão para 30%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 30 estimadores:")
print(cm)

Acurácia do modelo com 30 estimadores: 0.6833333333333333
Matriz de confusão para 30 estimadores:
[[88 42]
 [34 76]]


In [58]:
# Instanciando Random Forest
rf = RandomForestClassifier(n_estimators=100, criterion="log_loss", max_depth=None)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Acurácia do modelo
acuracia = metrics.accuracy_score(y_test, y_pred)
print("Acurácia do modelo com 100 estimadores:", acuracia)

# Matriz de confusão para 100%
cm = confusion_matrix(y_test, y_pred)
print("Matriz de confusão para 100 estimadores:")
print(cm)

Acurácia do modelo com 100 estimadores: 0.6916666666666667
Matriz de confusão para 100 estimadores:
[[89 41]
 [33 77]]
